import Head from 'next/head';
import Articles from '../components/Articles';
import Resource from '../components/Resource';
import NewsLetter from '../components/NewsLetter';
import Layout from '../components/Layout';

export default function Home({resources}) {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"></link>
      </Head>
      <Layout>
        {/* Resource */}
          <Resource resources={resources.slice(0, 2)} />
        
        {/* newsletter */}
          <NewsLetter />

        {/* Articles */}
          <Articles resources={resources.slice(2)} />
      </Layout>
    </>
  )
}

export async function getServerSideProps() {
  const resData = await fetch('http://localhost:3001/api/resource')
  const data = await resData.json()
  return {
    props: {
      resources: data
    }
  }
}
